# Project: Proyecto 3 parte 3
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Feetinches.o main.o Roomcarpet.o RoomDimension.o
LINKOBJ  = Feetinches.o main.o Roomcarpet.o RoomDimension.o
LIBS     = -L"C:/Programacion/C++/Dev-Cpp/MinGW64/lib" -L"C:/Programacion/C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Programacion/C++/Dev-Cpp/MinGW64/include" -I"C:/Programacion/C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Programacion/C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Programacion/C++/Dev-Cpp/MinGW64/include" -I"C:/Programacion/C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Programacion/C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Programacion/C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "Proyecto 3 parte 3.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Feetinches.o: Feetinches.cpp
	$(CPP) -c Feetinches.cpp -o Feetinches.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Roomcarpet.o: Roomcarpet.cpp
	$(CPP) -c Roomcarpet.cpp -o Roomcarpet.o $(CXXFLAGS)

RoomDimension.o: RoomDimension.cpp
	$(CPP) -c RoomDimension.cpp -o RoomDimension.o $(CXXFLAGS)
