# Project: Proyecto 2 parte 2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Informacion.o
LINKOBJ  = main.o Informacion.o
LIBS     = -L"C:/Programacion/C++/Dev-Cpp/MinGW64/lib" -L"C:/Programacion/C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Programacion/C++/Dev-Cpp/MinGW64/include" -I"C:/Programacion/C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Programacion/C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Programacion/C++/Dev-Cpp/MinGW64/include" -I"C:/Programacion/C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Programacion/C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Programacion/C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "Proyecto 2 parte 2.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Informacion.o: Informacion.cpp
	$(CPP) -c Informacion.cpp -o Informacion.o $(CXXFLAGS)
